name: build-and-push

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

env:
  IMAGE_NAME: ghcr.io/jakobrathberger/gh-action-demo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Package
        run: ./mvnw clean package -DskipTests

      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          file: ./src/main/docker/Dockerfile.jvm
          push: ${{ github.event_name != 'pull_request' }}
          tags: latest
          labels: ${{ env.IMAGE_NAME }}
          #tags: ${{ steps.meta.outputs.tags }}
          #labels: ${{ steps.meta.outputs.labels }}
          #cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          #cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max


